In [1]:
x = [2, 4, 6]
y = [3,5,6]

In [3]:
for xi, yi in zip(x,y):
    print(xi+yi)

5
9
12


In [4]:
z = []
for xi, yi in zip(x,y):
    z.append (xi + yi)
z

[5, 9, 12]

In [5]:
[ xi+yi for xi,yi in zip(x,y)] #list Comprenhensions

[5, 9, 12]

In [7]:
[xi**2 for xi in x]

[4, 16, 36]

In [34]:
import numpy as np

In [10]:
x = np.array([2, 1, 3])
y = np.array([4, 6, 7])

print (x+y)
print(type(x))

[ 6  7 10]
<class 'numpy.ndarray'>


In [11]:
x * 4000

array([ 8000,  4000, 12000])

In [12]:
lista = [2,3,4,5,6]
print(lista*5)
print(x*5)

[2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6]
[10  5 15]


In [15]:
x = np.array([2, 1, 3]) #Producto punto
y = np.array([4, 6, 7])
np.sum(x*y), x.dot(y), y.dot(x), x@y, x*y

(35, 35, 35, 35, array([ 8,  6, 21]))

In [17]:
A = np.array([[1,3,4],[1,0,0],[1,2,2]])

B = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])
print(A)
print(B)

[[1 3 4]
 [1 0 0]
 [1 2 2]]
[[1 0 5]
 [7 5 0]
 [2 1 1]]


In [18]:
A + B


array([[2, 3, 9],
       [8, 5, 0],
       [3, 3, 3]])

In [21]:
B@A

array([[ 6, 13, 14],
       [12, 21, 28],
       [ 4,  8, 10]])

In [22]:
A@B

array([[30, 19,  9],
       [ 1,  0,  5],
       [19, 12,  7]])

In [23]:
A.size

9

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [28]:
np.eye?

In [39]:
B = np.array([[1],
      [11]])
A = np.array([[1,-2],
      [3,2]])
A_inv = np.linalg.inv(A)
X = A_inv@B
X

array([[3.],
       [1.]])

In [ ]:
A = np.array([[1,2,3],
              [2,5,2],
              [6, -3, 1]])

In [ ]:
A = np.array([[3],[2],[4]])
B = np.array([[5],[3],[2]])
C = np.array([[6],[6],[6]])